# The relative path to your exposed web files.
document_root: docroot




# Specific settings for docker compose go here
docker_compose:

  # App services are docker compose images.
  # They will be added as-is to the generated docker-compose.yml file,
  # And attached automatically to the "app" container.
  app_services:
    storage:
      image: mongo

    # You can map a folder in an app_services container to a folder in your app by using {APP_PATH}
    solr:
      image: terra/solr
      volumes:
        - '{APP_PATH}/solr-config:/opt/solr/server/solr/core/conf'

